baseURL = "https://jjv.sh/"
languageCode = "en-us"
title = "jjv.sh"
theme = "hugowncast"
timeout = "5m"
disablePathToLower = true
cleanDestinationDir = false
ignoreFiles = ["gallery/.*"]

[markup.goldmark.renderer]
  unsafe = true

[permalinks]
  tags = "/:title/"

[params]
  description = "Jane Vandegriff's website and livestream, including games, videos, blog, drawings, music, electronics projects, and more."
  author = "Jane Vandegriff"
  image = "https://jjv.sh/logo"

[menu]
  [[menu.main]]
    name = "home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "games"
    url = "https://games.jjv.sh/"
    weight = 2
  [[menu.main]]
    name = "blog"
    url = "/blog/"
    weight = 3
  [[menu.main]]
    name = "featured"
    url = "/featured/"
    weight = 4
  [[menu.main]]
    name = "poetry"
    url = "/poetry/"
    weight = 5
  [[menu.main]]
    name = "videos"
    url = "/videos/"
    weight = 6
  [[menu.main]]
    name = "gallery"
    url = "/gallery/"
    weight = 7
  [[menu.main]]
    name = "resume"
    url = "/resume/"
    weight = 8
  [[menu.main]]
    name = "about"
    url = "/about/"
    weight = 9
  [[menu.main]]
    name = "now"
    url = "/now/"
    weight = 10
  [[menu.main]]
    name = "contact"
    url = "/contact/"
    weight = 11
